name: Build and push docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build and push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/evilhamsterman/http-echo

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
